Derryk/feature/userposts
bbd-grad-levelups/Bean-Enthusiasts pull request #7
Opened 2024-03-09 14:58 UTC by DerrykBBD

Create user posts

2024-03-09 19:57 UTC, jhviljoen requested changes
Just have a look at making the client changes functions to keep it clean please. Otherwise, looks good.

2024-03-09 19:57 UTC, jhviljoen commented on Client/src/main/java/com/bbd/BeanClient/ClientApplication.java
I humbly request that you start putting these tests into functions. This will allow us to have multiple tests in the file that can we can switch between easily through the course of the project (especially when Stefan starts the actual CLI commands)

2024-03-09 19:57 UTC, jhviljoen commented on Server/src/main/java/com/bbd/BeanServer/controller/FavoriteBeanController.java
You made a FavoriteBeansController in one of the other pull requests. Is this different?

2024-03-09 19:57 UTC, jhviljoen commented on Server/src/main/java/com/bbd/BeanServer/model/Post.java
This looks much more robust than the one I threw together. Consider using @NoArgsConstructor instead of defining it yourself?

2024-03-09 19:57 UTC, jhviljoen commented on Server/src/main/java/com/bbd/BeanServer/model/FavoriteBean.java
Same comments as Post.java

2024-03-09 19:57 UTC, jhviljoen commented on Client/src/main/java/com/bbd/BeanClient/ClientApplication.java
Have you considered using RestTemplate/WebClient? They seem to be better wrappers for doing requests.

2024-03-10 06:30 UTC, DerrykBBD commented on Client/src/main/java/com/bbd/BeanClient/ClientApplication.java
agreed , put them into functions. I am using RestTemplate for the request , it does look a bit messy I tried by making a post object client side, but you have to specify the dependency in maven and spring boot doesn't like it.

2024-03-10 06:30 UTC, DerrykBBD commented on Server/src/main/java/com/bbd/BeanServer/controller/FavoriteBeanController.java
No, I just changed the naming convention.

2024-03-10 06:54 UTC, DerrykBBD commented on Server/src/main/java/com/bbd/BeanServer/model/Post.java
Changed

2024-03-10 07:00 UTC, jhviljoen commented on Server/src/main/java/com/bbd/BeanServer/controller/FavoriteBeanController.java
Might need to merge in main and do the deletion to make git happy

2024-03-10 07:43 UTC, jhviljoen approved these changes
Happy with this, thanks for the effort.

2024-03-10 07:44 UTC, merged